/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as FishingZonesRouteImport } from './routes/fishing-zones'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as MapRouteImport } from './routes/map'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RouteRiskRouteImport } from './routes/route-risk'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as TermsRouteImport } from './routes/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const FishingZonesRoute = FishingZonesRouteImport.update({
  id: '/fishing-zones',
  path: '/fishing-zones',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteRiskRoute = RouteRiskRouteImport.update({
  id: '/route-risk',
  path: '/route-risk',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/fishing-zones': typeof FishingZonesRoute
  '/forecast': typeof ForecastRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/route-risk': typeof RouteRiskRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/fishing-zones': typeof FishingZonesRoute
  '/forecast': typeof ForecastRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/route-risk': typeof RouteRiskRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/fishing-zones': typeof FishingZonesRoute
  '/forecast': typeof ForecastRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/route-risk': typeof RouteRiskRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/fishing-zones'
    | '/forecast'
    | '/map'
    | '/privacy'
    | '/route-risk'
    | '/settings'
    | '/sources'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/fishing-zones'
    | '/forecast'
    | '/map'
    | '/privacy'
    | '/route-risk'
    | '/settings'
    | '/sources'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/fishing-zones'
    | '/forecast'
    | '/map'
    | '/privacy'
    | '/route-risk'
    | '/settings'
    | '/sources'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  FishingZonesRoute: typeof FishingZonesRoute
  ForecastRoute: typeof ForecastRoute
  MapRoute: typeof MapRoute
  PrivacyRoute: typeof PrivacyRoute
  RouteRiskRoute: typeof RouteRiskRoute
  SettingsRoute: typeof SettingsRoute
  SourcesRoute: typeof SourcesRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fishing-zones': {
      id: '/fishing-zones'
      path: '/fishing-zones'
      fullPath: '/fishing-zones'
      preLoaderRoute: typeof FishingZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-risk': {
      id: '/route-risk'
      path: '/route-risk'
      fullPath: '/route-risk'
      preLoaderRoute: typeof RouteRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  FishingZonesRoute: FishingZonesRoute,
  ForecastRoute: ForecastRoute,
  MapRoute: MapRoute,
  PrivacyRoute: PrivacyRoute,
  RouteRiskRoute: RouteRiskRoute,
  SettingsRoute: SettingsRoute,
  SourcesRoute: SourcesRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
